### ISSUE TITLE
Issue opening issues 😂

### ISSUE THREAD

**Issue by simplemachine92** [Talent-DAO/eas-front-end#12]
When opening an issue here, if you select anything but the "blank issue" option or the "Get Started" button by "bug report", this directs you to SE2 repo, presumably opening a discussion there.

Which is strange because the [github docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks) say this shouldn't happen.

Can anyone else confirm this issue?

Anyway, might be a problem in the future for obv reasons.

**Comment by codenamejason** [comment]
Good call-out. I will fix that.
